### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by nakano16180** [rionehome/help_me_carry#2]
## 概要
help_me_carryの音声系のコードをリファクタリング・統合します。

## ブランチ名
  - code_refactoring

## 対象コード
- pkgs/help_me_nlp_first_half/
- pkgs/help_me_nlp_second_half/
- pkgs/hmc_follow_me_nlp/

**Comment by Nenetti** [comment]
コメントも出来るだけ書いてよろしく

**Comment by HiroRittsu** [comment]
firstのリファクタリングの重さを考えて、作業分担を提案す。

**Comment by nakano16180** [comment]
分担を考えたけど、最終的に上の3つのパッケージを統合することを考えると一人でやったほうが良いかも。以下の3つのファイルを一つのパッケージに入れる形で統合予定

- recognition.py
  - 音声認識
- main.py
  - 音声認識の結果の文章を受けて、自然言語処理
- speak.py
  - 発話

**Comment by HiroRittsu** [comment]
3つのパッケージ統合は問題ないけど、speakとrecognittionはねねっちのsoundsystemのやつを使うほうが管理しやすくない？

**Comment by nakano16180** [comment]
確かに。
じゃあ、main.pyだけリファクタリングしてsound_systemにつなげます

**Comment by takoyan** [comment]
help.pyのyes_no_recognition関数内の処理について
対話者に場所を3回まで言い直してもらう処理ができていないです.
