### ISSUE TITLE
リファクタリング byねねっち

### ISSUE THREAD

**Issue by Nenetti** [rionehome/help_me_carry#3]
# 概要
help_me_carryのリファクタリング

ブランチ名
nenecchi_refactoring

対象コード
pkgs/hmc_human_detection
pkgs/hmc_navigation

**Comment by HiroRittsu** [comment]
おっとすまん、hmc_navigationは結局使わなかったので削除の方向でお願いします

**Comment by Nenetti** [comment]
まじか
了解ですわ
